# Generated by Django 5.2.8 on 2025-11-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Фото категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва сукні')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за добу (грн)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Застава (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('age_range', models.CharField(max_length=50, verbose_name='Вік (напр. 3-4 роки)')),
                ('size_label', models.CharField(blank=True, max_length=50, verbose_name='Розмір на бірці')),
                ('image_ratio', models.FloatField(default=1.0, verbose_name='Пропорція фото (для сітки)')),
                ('cleaning_days', models.PositiveIntegerField(default=2, help_text='Скільки днів автоматично додавати після оренди', verbose_name='Авто-хімчистка (днів)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Відображати на сайті')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='dresses', to='shop.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Сукня',
                'verbose_name_plural': 'Сукні',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(verbose_name='Кінець')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('confirmed', 'Підтверджено'), ('active', 'В оренді'), ('completed', 'Завершено'), ('canceled', 'Скасовано'), ('maintenance', '🔴 ТЕХНІЧНЕ БЛОКУВАННЯ (Ремонт/Хімчистка)')], default='new', max_length=20, verbose_name='Статус')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name="Ім'я клієнта")),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shop.dress', verbose_name='Сукня')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Календар зайнятості',
            },
        ),
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dresses/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.dress')),
            ],
            options={
                'verbose_name': 'Фото сукні',
                'verbose_name_plural': 'Фото суконь',
            },
        ),
    ]
